[package]
name = "to-do-rocket-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
to-do-core = { path = "../../core" }
glue = { path = "../../../../glue", features = ["rocket"] }
to-do-dal = { path = "../../dal", features = ["sqlx-postgres"]}
auth-kernel = { path = "../../../auth/kernel" }

[features]
auth-http = ["auth-kernel/http"]
auth-core-postgres = ["auth-kernel/core-postgres"]
default = ["auth-core-postgres"]