[package]
name = "to-do-http-workflow-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
to-do-kernel = { path = "../../kernel", features = ["http"] }
auth-kernel = { path = "../../../auth/kernel", features = ["http"] }
auth-core = { path = "../../../auth/core" }
tokio = { version = "1.16.1", features = ["full"] }
dal  = { path = "../../dal", features = ["sqlx-postgres"] }
auth-dal = { path = "../../../auth/dal" }
glue = { path = "../../../../glue" }
sqlx = { version = "0.7.4", features = ["postgres", "json", "runtime-tokio"] }
