[package]
name = "auth-hyper-server"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "1.2.0", features = ["full"] }
tokio = { version = "1.36.0", features = ["full"] }
http-body-util = "0.1.1"
hyper-util = { version = "0.1.3", features = ["full"] }
serde_json = "1.0.128"
bytes = "1.7.1"
auth-core = { path = "../../core" }
glue = { path = "../../../../glue", features = ["hyper"] }
serde = { version = "1.0.197", features = ["derive"] }
auth-dal = { path = "../../dal" }
base64 = "0.22.1"
auth-kernel = { path = "../../kernel", features = ["auth-core"], default-features = false }
